# Generated by Django 3.0 on 2023-05-05 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20230505_0102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
